### PR TITLE
Proper "export" header for library consumers

### PR DESCRIPTION
**Pull request by DarkWanderer**

### CODE REVIEW

**Review by X39 — CHANGES_REQUESTED** [review]
The renamed files are named wrong
`sqlvm.*` compared to the expected `sqfvm.*`

**Comment by DarkWanderer** [comment]
Oops - I can't blame it on autocorrect now, can I?
Fixed

**Comment by DarkWanderer** [comment]
Hm, unexpected failures - will revisit

**Comment by X39** [comment]
Could also mark this as WIP

**Pull request closed without merging**
