### PR TITLE
--pretty-print command reimplementation

### PR DESCRIPTION
**Pull request by Casperento**
I've started the reimplementation of the old --pretty-print command.

Result example (`sqfvm --automated --parse-only --pretty-print filename.sqf`):
https://pastebin.com/RaT1Swww

Currently, build is passing all cmake tests (tested on Windows and Linux). I've been trying to modify less code as possible, so maybe I've missed something 😅

### CODE REVIEW

**Comment by X39** [comment]
Could you move this out of the parser and put it into a separate class (thinking of possibly modifying this in the future to allow customization)

**Comment by Casperento** [comment]
I'm having trouble when trying to reference the parser inside a new class for the sqf formatter:

- class constructor' impl:

```cpp
::sqf::parser::sqf::formatter::formatter(::sqf::runtime::runtime& r, ::sqf::parser::sqf::parser& p_ptr, std::string c, ::sqf::runtime::fileio::pathinfo f) : runtime{ r }, contents{ c }, file{ f } {
    tokenizer t(contents.begin(), contents.end(), file.physical);
    ::sqf::parser::sqf::bison::parser p(t, this->res, p_ptr, this->runtime);
    this->hasError = p.parse() != 0;
}
```

- constructor usage example:

```cpp
::sqf::parser::sqf::formatter fmt(m_runtime, m_runtime.parser_sqf(), str, {path.string(), {}});
```

- 'm_runtime.parser_sqf()' type is 'sqf::runtime::parser::sqf'...then i got the following error:

'C++ no instance of constructor matches the argument list argument types are: (sqf::runtime::runtime, sqf::runtime::parser::sqf, std::string, {...})'

**Comment by Casperento** [comment]
Sorry for the last comment.

I managed to fix the issue and created a new class called `formatter` successfully. 

Build is still passing cmake tests.

**Comment by X39** [comment]
There is no need to sorry.

Thanks, will check the full pr tomorrow :)

**Review by X39 — APPROVED** [review]

**Comment by X39** [comment]
Minor changes are technically required (`+=` vs `<<`)

**Pull request merged**
